name: 'Terraform'

on:
  push:
    branches:
    - master
  pull_request:

jobs:

############ Development ############

  DeployDev:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    continue-on-error: true
    environment:
      name: Dev

    steps:

    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2.1.1
      with:
        url: https://vault-cluster.vault.3d3539c1-53f1-4599-b60f-553fee88a921.aws.hashicorp.cloud:8200/
        token: ${{ secrets.VAULT_TOKEN }}
        continue-on-error: true
        tlsSkipVerify: true
        namespace: admin
        secrets: |
              kv/tfe token | TFC_TEAM_TOKEN


    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ steps.secrets.outputs.TFC_TEAM_TOKEN }}
        cli_config_credentials_hostname: 'iacdev.wpp.cloud'


    - name: Terraform Init
      run: terraform init -input=false
      env:
        TF_WORKSPACE: "dev"
        TF_IN_AUTOMATION: "true"

    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Plan
      run: terraform plan -input=false
      env:
        TF_WORKSPACE: "dev"
        TF_IN_AUTOMATION: "true"

    - name: Terraform Apply
      run: terraform apply -input=false -auto-approve
      env:
        TF_WORKSPACE: "dev"
        TF_IN_AUTOMATION: "true"



############ Production ###############

  DeployProd:
    name: Deploy to prod
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: prod

    steps:


    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2.1.1
      with:
        url: https://vault-cluster.vault.3d3539c1-53f1-4599-b60f-553fee88a921.aws.hashicorp.cloud:8200/
        token: ${{ secrets.VAULT_TOKEN }}
        continue-on-error: true
        tlsSkipVerify: true
        namespace: admin
        secrets: |
              kv/tfe token | TFC_TEAM_TOKEN


    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ steps.secrets.outputs.TF_TEAM_TOKEN }}
        cli_config_credentials_hostname: 'iacdev.wpp.cloud'


    - name: Terraform Init
      run: terraform init -input=false
      env:
        TF_WORKSPACE: "prod"
        TF_IN_AUTOMATION: "true"

    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Plan
      run: terraform plan -input=false
      env:
        TF_WORKSPACE: "prod"
        TF_IN_AUTOMATION: "true"

    - name: Terraform Apply
      run: terraform apply -input=false -auto-approve
      env:
        TF_WORKSPACE: "prod"
        TF_IN_AUTOMATION: "true"
